# Generated by Django 5.1.1 on 2024-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_healthgoal_recommendation_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('healthcare_provider', 'Healthcare Provider'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
