# Generated by Django 5.1.1 on 2024-10-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_healthmetric_age_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='health_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app1.healthgoal'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='health_metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app1.healthmetric'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='content',
            field=models.TextField(help_text='Personalized health recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
