# Generated by Django 5.1.1 on 2024-10-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_recommendation_health_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='health_goal',
        ),
    ]
