# Generated by Django 5.1.1 on 2024-10-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_recommendation_health_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='health_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.healthgoal'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='health_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app1.healthmetric'),
        ),
    ]
