# Generated by Django 5.1.1 on 2024-10-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_recommendation_health_goal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='content',
            new_name='recommendation_text',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='health_goal',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='health_metric',
        ),
    ]
